---
title: "DADA2_to_Phyloseq_object"
author: "Joy O'Brien"
date: "2024-11-10"
output: html_document
---

```{r}
install.packages("dplyr")
install.packages("readxl")    
install.packages("ggplot2")   
install.packages("phyloseq")
if (!require("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("phyloseq")
```

```{r}
# Load packages 
library("phyloseq")
library("ggplot2")      # graphics
library("readxl")       # necessary to import the data from Excel file
library("dplyr")        # filter and reformat data frames
library("tibble")       # Needed for converting column to row names
library("vegan")        #Used for rarifying
```

```{r}
# Read in phyloseq object and see if all 3 datasets can be separated
phylo <- readRDS("~/GitHub/thaw.response/Data/new_merged_phyloseqobj.rds")

# Extract the data from the phyloseq object
seq_tab.raw <- as.data.frame(otu_table(phylo))
taxonomy <- as.data.frame(tax_table(phylo))
metadata <- as.data.frame(sample_data(phylo))

# Merge consensus sequence to ASV ID numbers
# Load key 
ASV_OTU_key <- read.table("~/GitHub/thaw.response/Data/ASVnumber_OTUid_key.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# Convert row names to sequence
seq_tab.raw$sequence <- rownames(seq_tab.raw)

# Check that these columns are not factors
seq_tab.raw$sequence <- as.character(seq_tab.raw$sequence)
ASV_OTU_key$sequence <- as.character(ASV_OTU_key$sequence)

# Merge 
seq_tab <- merge(seq_tab.raw, ASV_OTU_key, by = "sequence", all.x = TRUE)

# Reorder columns: Bring ASV_OTU_key columns to the front
seq_tab <- seq_tab[, c(colnames(ASV_OTU_key), setdiff(colnames(seq_tab), colnames(ASV_OTU_key)))]

head(seq_tab)

# Do the same for the taxonomy
# Convert row names to sequence
taxonomy$sequence <- rownames(taxonomy)

# Check that these columns are not factors
taxonomy$sequence <- as.character(taxonomy$sequence)
ASV_OTU_key$sequence <- as.character(ASV_OTU_key$sequence)

# Merge 
taxonomy <- merge(taxonomy, ASV_OTU_key, by = "sequence", all.x = TRUE)

# Reorder columns: Bring ASV_OTU_key columns to the front
taxonomy <- taxonomy[, c(colnames(ASV_OTU_key), setdiff(colnames(taxonomy), colnames(ASV_OTU_key)))]

head(taxonomy)

# Remove the sequence column from seqtab because it causes problems downstream
seq_tab$sequence <- NULL

```


OLD
```{r}
# Read the data into R from excel file incubation_16S_reseq.xlsx 
seq_tab.raw <- readRDS("~/GitHub/thaw.response/Data/new_mergedASVtab_Joy.rds") # fill this in with the file path for your DADA2 seqtab output
taxonomy <- read("~/GitHub/Masters_publication/meta_sequence_data.xlsx", sheet = "tax_final_dada2merge", na = c("","NA")) # fill this in with the tax_final file DADA2 output
metadata <- read_excel("~/GitHub/Masters_publication/meta_sequence_data.xlsx", sheet = "metadata_final_combined") # fill this in with the metadata file
```

OLD
```{r}
# Define row names from the ASV column 
seq_tab <- seq_tab.raw %>%
  tibble::column_to_rownames("ASV_ID") 

taxonomy <- taxonomy %>%
  tibble::column_to_rownames("ASV_ID") 

metadata <- metadata %>% 
  tibble::column_to_rownames("sample_name") %>% 
  mutate(sample_blank = ifelse(test = grepl("BLANK", sample_ID), no = "Sample", yes = "BLANK")) %>%
  mutate(core_rep = gsub("_POST_SOIL", "", sample_ID)) %>%
  mutate(core_rep = gsub("_PRE_SOIL", "", core_rep))
```



```{r}
# Transform into matrices 
seq_tab <- as.matrix(seq_tab)
taxonomy <- as.matrix(taxonomy)

# Transform to phyloseq objects
ASV <- otu_table(seq_tab, taxa_are_rows = TRUE) 
TAX <- tax_table(taxonomy)
samples = sample_data(metadata)

# Create the phyloseq object
thaw <- phyloseq(ASV, TAX, samples) 

# Prune samples from the phyloseq object dorm created above, and call the pruned object dorm1
thaw1 <- prune_samples(sample_sums(thaw) > 0,thaw)
thaw1 #17073 axa

# Remove taxa that are unassigned at the Phylum level
thaw1 <- subset_taxa(thaw1, !is.na(Phylum)) # Note that sample blanks are still included here 
thaw1 # went from 17073 to 16048 (decrease due to deleting those that are unassigned at phylum level)

# The number of taxa that were removed from being unassigned at the Phylum level: 17073-16048 = 1025
# Filtering chloroplasts and mitochondria
thaw1 <- subset_taxa(thaw1, Family != "Mitochondria")
thaw1 <- subset_taxa(thaw1, Order != "Chloroplast") 
# check to see if mitochondria and chloroplasts were removed
thaw1  # 9213 taxa
# Number of taxa removed from mitochondria and chloroplasts: 16048-9213 = 6835 # calculate as % reads for publication --> 42.6%
```

```{r}
# Remove sequence blanks from the data set and PCR blanks and FL1C4 REP 8 POST THAW
thaw_noblank <- subset_samples(thaw1, !(sample_ID %in% c("PCR_BLANK", "DNA_BLANK_1_POST_THAW_SOIL", "DNA_BLANK_1_PRE_THAW_SOIL", "DNA_BLANK_2_POST_THAW_SOIL", "DNA_BLANK_2_PRE_THAW_SOIL", "FL1C4_R8_POST_SOIL")))

# Check to see if samples were removed (should be 5 for the re-seq round)
thaw_noblank # this checks out, 6 samples were removed
```

```{r}
# Extract the OTU table from the phyloseq object
otu_table <- otu_table(thaw_noblank)

# Convert the OTU table to a matrix if it's not already
otu_matrix <- as(otu_table, "matrix")

# Calculate the sum of ASV counts per sample
asv_sums <- colSums(otu_matrix)

# Print the results
print(asv_sums)
hist(asv_sums)

```

```{r}
# Print the sums per sample
print(asv_sums)

# Visualize with a histogram
hist(sort(colSums(otu_table(thaw_noblank)))) 

# Rarefying the data 
otu_rarify <- as.data.frame(thaw_noblank@otu_table)
rarecurve(otu_rarify, step = 50, cex = 0.5, label = FALSE)
thaw.rarify <- rarefy_even_depth(thaw_noblank, rngseed = 1, sample.size = 5000, replace = FALSE)

# Now let's check the rarifaction plot after rarifying 
rarify.check <- as.data.frame(thaw.rarify@otu_table)
rarecurve(rarify.check, step = 50, cex = 0.5, label = FALSE)



# Create the rarified OTU table
otu.rarify.table <- otu_table(thaw.rarify)
```

```{r}
# Transform the OTU table 
thaw_transformed <- t(sqrt(otu.rarify.table))

# Create a distance matrix using vegan and bray
dm_thaw <- vegdist(thaw_transformed, method = "bray")
# I did the following to check how many samples made it through rarifaction
dm_thaw_mat <- as.matrix(dm_thaw)

# Run an NMDS (stress values indicate how well the variation is represented, stress less than 0.05 is good, below 0.3 is poor, below 0.2 is okay) pp: NIce comment, here's the link for that info: https://jonlefcheck.net/2012/10/24/nmds-tutorial-in-r/
thaw.nmds <- metaMDS(dm_thaw, k = 2, trymax = 1500) ## "k" is the number of axes, sometimes 2 is not enough, "trymax" is the number of times it tries to find solutions
print(thaw.nmds)
plot(thaw.nmds)

```
Exploring PCoA plot instead of nmds
```{r}
# Transform the OTU table 
thaw_transformed <- t(sqrt(otu.rarify.table))

# Create a distance matrix using vegan and bray
dm_thaw <- vegdist(thaw_transformed, method = "bray")

thaw.pcoa <- ordinate(thaw.rarify, method = "PCoA", distance = dm_thaw)
print(thaw.pcoa)


plot_ordination(
  physeq = thaw.rarify,
  ordination = thaw.pcoa,
  color = "site",
  shape = "pre_post_thaw"
) +
  geom_point(aes(color = site), alpha = 0.7, size = 4) +
  geom_point(size = 2) +
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  scale_color_manual(values = c("CRREL" = "#1b9e77", "FL" = "#d95f02", "Utqiagvik" = "#7570b3"), name = "Site") +  # Custom colors for site
  scale_shape_discrete("Treatment") +
  scale_shape_manual("Treatment", labels = c("Pre-thaw", "Post-thaw"), values = c(2, 1))
```
```{r}
# Changing the points so there are open and closed circle
# Making sure the legend will show pre before post
sample_data(thaw.rarify)$pre_post_thaw <- factor(
  sample_data(thaw.rarify)$pre_post_thaw,
  levels = c("pre", "post")  
)

# Extracting variance explained

eigvals <- thaw.pcoa$values$Relative_eig


x_var <- round(eigvals[1] * 100, 1)
y_var <- round(eigvals[2] * 100, 1)


plot_ordination(
  physeq = thaw.rarify,
  ordination = thaw.pcoa,
  color = "site",
  shape = "pre_post_thaw"
) +
  geom_point(aes(color = site), alpha = 0.7, size = 4) +
  geom_point(size = 2) +
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  scale_color_manual(
    values = c("CRREL" = "#1b9e77", "FL" = "#d95f02", "Utqiagvik" = "#7570b3"),
    name = "Site"
  ) +
scale_shape_manual(
  name = "Treatment",
  values = c("pre" = 1, "post" = 16),  # 1 = open circle, 16 = filled circle
  labels = c("pre" = "Pre-thaw", "post" = "Post-thaw")
) +
      labs(
    x = paste0("PCoA1 (", x_var, "%)"),
    y = paste0("PCoA2 (", y_var, "%)"))



# Now connect paired samples with dotted lines

```
```{r}

library(dplyr)
library(tidyr)
# Plotting again with dotted lines to connect the pre and post 
ordination_scores <- as.data.frame(thaw.pcoa$vectors)
ordination_scores$SampleID <- rownames(ordination_scores)
ordination_scores$Treatment <- sample_data(thaw.rarify)$pre_post_thaw
ordination_scores$Site <- sample_data(thaw.rarify)$site

# If you have a variable to match pre/post pairs (e.g. `core_id`), add it:
ordination_scores$sample_id <- sample_data(thaw.rarify)$sample_id

library(dplyr)

line_segments <- ordination_scores %>%
  select(SampleID, SampleID, Treatment, Axis.1, Axis.2) %>%
  pivot_wider(names_from = Treatment, values_from = c(Axis.1, Axis.2)) %>%
  drop_na()  # Remove any incomplete pairs

plot_ordination(
  physeq = thaw.rarify,
  ordination = thaw.pcoa,
  color = "site",
  shape = "pre_post_thaw"
) +
  # Dotted lines connecting pre/post
  geom_segment(
  data = line_segments,
  aes(x = Axis.1_pre, y = Axis.2_pre, xend = Axis.1_post, yend = Axis.2_post),
  linetype = "dotted", color = "gray50", size = 0.5,
  inherit.aes = FALSE
) +
  # Points
  geom_point(aes(color = site), alpha = 0.7, size = 4) +
  geom_point(size = 2) +
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  labs(
    x = paste0("PCoA1 (", round(thaw.pcoa$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA2 (", round(thaw.pcoa$values$Relative_eig[2] * 100, 1), "%)")
  ) +
  scale_color_manual(
    values = c("CRREL" = "#1b9e77", "FL" = "#d95f02", "Utqiagvik" = "#7570b3"),
    name = "Site"
  ) +
  scale_shape_manual(
    name = "Treatment",
    values = c("pre" = 1, "post" = 16),
    labels = c("pre" = "Pre-thaw", "post" = "Post-thaw")
  )

view(sample_data(thaw.rarify)[, c("pre_post_thaw", "core")])
view(line_segments)

table(sample_data(thaw.rarify)$pre_post_thaw)
anyDuplicated(sample_data(thaw.rarify)$core)

```
```{r}
# Extract sample coordinates from the PCoA object
ordination_scores <- as.data.frame(thaw.pcoa$vectors)
ordination_scores$sample_ID <- rownames(ordination_scores)

# Extract metadata
metadata <- data.frame(sample_data(thaw.rarify))
metadata$sample_ID <- rownames(metadata)

# Merge scores with metadata
ordination_scores <- left_join(ordination_scores, metadata, by = "sample_ID")

library(dplyr)
library(tidyr)

line_segments <- ordination_scores %>%
  filter(pre_post_thaw %in% c("pre", "post")) %>%
  select(core, pre_post_thaw, Axis.1, Axis.2) %>%
  pivot_wider(
    names_from = pre_post_thaw,
    values_from = c(Axis.1, Axis.2),
    names_sep = "_"
  ) %>%
  drop_na()

colnames(ordination_scores)


head(line_segments)


ordination_scores %>%
  count(core, pre_post_thaw) %>%
  filter(n > 1)


library(dplyr)
library(tidyr)

# Summarize to one row per core per pre/post thaw group
line_segments <- ordination_scores %>%
  filter(pre_post_thaw %in% c("pre", "post")) %>%
  group_by(core, pre_post_thaw) %>%
  summarize(
    Axis.1 = mean(Axis.1),
    Axis.2 = mean(Axis.2),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = pre_post_thaw,
    values_from = c(Axis.1, Axis.2),
    names_sep = "_"
  ) %>%
  drop_na()  # drops rows missing either pre or post coords


plot_ordination(
  physeq = thaw.rarify,
  ordination = thaw.pcoa,
  color = "site",
  shape = "pre_post_thaw"
) +
  # Dotted lines connecting pre/post
  geom_segment(
  data = line_segments,
  aes(x = Axis.1_pre, y = Axis.2_pre, xend = Axis.1_post, yend = Axis.2_post),
  linetype = "dotted", color = "gray50", size = 0.5,
  inherit.aes = FALSE
) +
  # Points
  geom_point(aes(color = site), alpha = 0.7, size = 4) +
  geom_point(size = 2) +
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  labs(
    x = paste0("PCoA1 (", round(thaw.pcoa$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA2 (", round(thaw.pcoa$values$Relative_eig[2] * 100, 1), "%)")
  ) +
  scale_color_manual(
    values = c("CRREL" = "#1b9e77", "FL" = "#d95f02", "Utqiagvik" = "#7570b3"),
    name = "Site"
  ) +
  scale_shape_manual(
    name = "Treatment",
    values = c("pre" = 1, "post" = 16),
    labels = c("pre" = "Pre-thaw", "post" = "Post-thaw")
  )


```
Okay so the above code shows the lines by core 
but we want to connect lines to inidivudal samples
```{r}
library(dplyr)
library(tidyr)
library(phyloseq)
library(ggplot2)

# 1. Extract ordination scores from your PCoA object
ordination_scores <- as.data.frame(thaw.pcoa$vectors)
ordination_scores$sample_ID <- rownames(ordination_scores)

# 2. Extract metadata from phyloseq
metadata <- data.frame(sample_data(thaw.rarify))
metadata$sample_ID <- rownames(metadata)

# 3. Merge ordination scores with metadata
ordination_scores <- left_join(ordination_scores, metadata, by = "sample_ID")

# 4. Create a cleaned pair_ID by removing the pre/post suffix from sample_ID
#    Adjust regex to your sample ID naming pattern as needed
ordination_scores <- ordination_scores %>%
  mutate(pair_ID = gsub("_(PRE|POST).*", "", sample_ID),
         pre_post_thaw = tolower(pre_post_thaw))  # just in case pre_post_thaw is mixed case

# 5. Pivot to get pre and post sample coordinates side-by-side for line plotting
line_segments <- ordination_scores %>%
  select(pair_ID, pre_post_thaw, Axis.1, Axis.2) %>%
  pivot_wider(names_from = pre_post_thaw, values_from = c(Axis.1, Axis.2)) %>%
  drop_na()  # drop pairs where either pre or post is missing

# 6. Plot using plot_ordination + ggplot, adding geom_segment to connect pairs

# Base ordination plot with default data (phyloseq)
base_plot <- plot_ordination(
  physeq = thaw.rarify,
  ordination = thaw.pcoa,
  color = "site",
  shape = "pre_post_thaw"
)

# Add the segments and points layers explicitly specifying data and mappings
base_plot +
  geom_segment(
    data = line_segments,
    aes(x = Axis.1_pre, y = Axis.2_pre, xend = Axis.1_post, yend = Axis.2_post),
    linetype = "dotted", color = "black", inherit.aes = FALSE
  ) +
  geom_point(alpha = 0.7, size = 4) +  # inherits color and shape from base_plot
  geom_point(size = 2) +
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  labs(
    x = paste0("PCoA1 (", round(thaw.pcoa$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA2 (", round(thaw.pcoa$values$Relative_eig[2] * 100, 1), "%)")
  ) +
  scale_color_manual(
    values = c("CRREL" = "#1b9e77", "FL" = "#d95f02", "Utqiagvik" = "#7570b3"),
    name = "Site"
  ) +
  scale_shape_manual(
    name = "Treatment",
    values = c("pre" = 1, "post" = 16, stroke = 1),
    labels = c("pre" = "Pre-thaw", "post" = "Post-thaw")
  )
```
```{r}
base_plot +
  geom_segment(
    data = line_segments,
    aes(x = Axis.1_pre, y = Axis.2_pre, xend = Axis.1_post, yend = Axis.2_post),
    linetype = "dotted", color = "black", inherit.aes = FALSE
  ) +
  geom_point(size = 3, alpha = 0.9) +  # Single point layer
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  labs(
    x = paste0("PCoA1 (", round(thaw.pcoa$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA2 (", round(thaw.pcoa$values$Relative_eig[2] * 100, 1), "%)")
  ) +
  scale_color_manual(
    values = c("CRREL" = "#1b9e77", "FL" = "#d95f02", "Utqiagvik" = "#7570b3"),
    name = "Site"
  ) +
  scale_shape_manual(
    name = "Treatment",
    values = c("pre" = 1, "post" = 16),  # Shape 1 = open circle, 16 = filled
    labels = c("pre" = "Pre-thaw", "post" = "Post-thaw")
  )

```


```{r}
plot_ordination(
  physeq = thaw.rarify,
  ordination = thaw.pcoa,
  color = "site",
  shape = "pre_post_thaw"
) +
  geom_segment(data = line_segments,
               aes(x = Axis.1_pre, y = Axis.2_pre,
                   xend = Axis.1_post, yend = Axis.2_post),
               linetype = "dotted", color = "black") +
  geom_point(aes(color = site), alpha = 0.7, size = 4) +
  geom_point(size = 2) +
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  labs(
    x = paste0("PCoA1 (", round(thaw.pcoa$values$Relative_eig[1] * 100, 1), "%)"),
    y = paste0("PCoA2 (", round(thaw.pcoa$values$Relative_eig[2] * 100, 1), "%)")
  ) +
  scale_color_manual(
    values = c("CRREL" = "#1b9e77", "FL" = "#d95f02", "Utqiagvik" = "#7570b3"),
    name = "Site"
  ) +
  scale_shape_manual(
    name = "Treatment",
    values = c("pre" = 1, "post" = 16),
    labels = c("pre" = "Pre-thaw", "post" = "Post-thaw")
  )






```


```{r}
plot_ordination(
  physeq = thaw.rarify,
  ordination = thaw.nmds,
  color = "site",
  shape = "pre_post_thaw",
  #title = "NMDS of Permafrost Bacterial Communities"
) +
  geom_point(aes(color = site), alpha = 0.7, size = 4) +
  geom_point(size = 2)+
  geom_text(aes(label = core), size = 4, color = "black") +
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  scale_color_discrete("Site") +
  scale_shape_discrete("Treatment") +
  scale_shape_manual("Treatment", labels = c("Pre-thaw", "Post-thaw"), values = c(2, 1))



```

```{r}
# For publication
library(ggplot2)
library(RColorBrewer)

plot_ordination(
  physeq = thaw.rarify,
  ordination = thaw.nmds,
  color = "site",
  shape = "pre_post_thaw"
) +
  geom_point(aes(color = site), alpha = 0.7, size = 4) +
  geom_point(size = 2) +
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  scale_color_brewer(palette = "Set1", name = "Site") +
  scale_shape_discrete("Treatment") +
  scale_shape_manual("Treatment", labels = c("Pre-thaw", "Post-thaw"), values = c(2, 1))
```


```{r}
library(ggplot2)
library(RColorBrewer)

plot_ordination(
  physeq = thaw.rarify,
  ordination = thaw.nmds,
  color = "site",
  shape = "pre_post_thaw"
) +
  geom_point(aes(color = site), alpha = 0.7, size = 4) +
  geom_point(size = 2) +
  theme_classic() +
  theme(axis.text = element_text(size = 18)) +
  scale_color_manual(values = c("CRREL" = "#1b9e77", "FL" = "#d95f02", "Utqiagvik" = "#7570b3"), name = "Site") +  # Custom colors for site
  scale_shape_discrete("Treatment") +
  scale_shape_manual("Treatment", labels = c("Pre-thaw", "Post-thaw"), values = c(2, 1))

```



```{r}
# Save the phyloseq object to yourfolder if this is your final object (save individual parts of the phyloseq object)

saveRDS(thaw.rarify,"~/GitHub/thaw.response/Data/thaw_phyloseq.rds")
saveRDS(thaw.rarify@otu_table,"~/GitHub/thaw.response/Data/thaw_OTU_phyloseq.rds")
saveRDS(thaw.rarify@tax_table,"~/GitHub/thaw.response/Data/thaw_tax_phyloseq.rds" )
saveRDS(thaw.rarify@sam_data,"~/GitHub/thaw.response/Data/thaw_metadata_phyloseq.rds")
```


```{r}
